[package]
name = "clevo-fan"
version = "0.0.0"
authors = ["Joshua Bachmeier"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99"
structopt = "0.3"
cpuio = "0.2"
nc = "0.4"
